# Generated by Django 5.2.18 on 2026-10-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('KML', 'KML'), ('SHAPEFILE', 'ESRI Shapefile')], max_length=16)),
                ('file_size', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('extracting', 'Extracting'), ('parsing', 'Parsing'), ('detecting_crs', 'Detecting Crs'), ('transforming', 'Transforming'), ('measuring', 'Measuring'), ('completed', 'Completed'), ('completed_with_errors', 'Completed With Errors'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('source_crs', models.JSONField(blank=True, null=True)),
                ('measurement_crs', models.JSONField(default=list)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('layers', models.JSONField(default=list)),
                ('components', models.JSONField(default=list)),
                ('geometry_types', models.JSONField(default=dict)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, null=True)),
                ('stages', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('is_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField()),
                ('source_id', models.CharField(blank=True, default='', max_length=255)),
                ('layer', models.CharField(blank=True, default='', max_length=255)),
                ('geometry_type', models.CharField(blank=True, default='', max_length=32)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('geometry_crs', models.CharField(blank=True, default='', max_length=64)),
                ('properties', models.JSONField(default=dict)),
                ('source_crs', models.CharField(blank=True, default='', max_length=64)),
                ('measurement_crs', models.CharField(blank=True, default='', max_length=64)),
                ('measurement_crs_name', models.CharField(blank=True, default='', max_length=128)),
                ('measurement_type', models.CharField(blank=True, default='', max_length=8)),
                ('measurement_value', models.FloatField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, default='', max_length=4)),
                ('geodesic_value', models.FloatField(blank=True, null=True)),
                ('measurement_status', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('unsupported', 'Unsupported')], max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.geofile')),
            ],
            options={
                'ordering': ['feature_index'],
                'constraints': [models.UniqueConstraint(fields=('file', 'feature_index'), name='unique_feature_index')],
            },
        ),
    ]
